name = "personal-inteligente"
type = "javascript"

account_id = "e1057b9d90ac5608b750b856533975eaac23f"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
name = "personal-inteligente-prod"
workers_dev = false
route = "https://seu-dominio.com/*"
zone_id = "SEU_ZONE_ID"
